Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  config.vm.network :private_network, ip: "192.168.56.63"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.provider "virtualbox" do |machine|
    machine.memory = 512
    machine.name = "control-node"
  end
  config.vm.provision "shell", path: "provision.sh"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }   
end
