Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network :private_network, ip: "192.168.56.62"
  config.vm.provider "virtualbox" do |machine|
    machine.memory = 1024
    machine.name = "Centos7"
  end
  config.vm.provision "shell", path: "provision.sh"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }   
end