---
- name: configurar servidor de banco de dados
  hosts: dbs
  user: vagrant
  become: yes
  vars_files:
    - vars/main.yml
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "devops"
  tasks:
    - name: configurar hosts lab ansible
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - 192.168.56.63 control-node
        - 192.168.56.64 app01
        - 192.168.56.65 db01
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql