Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "db01"
  config.vm.network :private_network, ip: "192.168.56.65"
  config.vm.network :forwarded_port, guest:3306, host:3306
  config.vm.provider "virtualbox" do |machine|
    machine.memory = 512
    machine.name = "db01"
  end
  config.vm.provision "shell", path: "provision.sh"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }   
end
